"""
E2GO Nodes - Оптимизированный набор нод для ComfyUI
Автор: Egor
"""

from .powder_lora import NODE_CLASS_MAPPINGS as LORA_NODES, NODE_DISPLAY_NAME_MAPPINGS as LORA_NAMES
from .powder_prompt import NODE_CLASS_MAPPINGS as PROMPT_NODES, NODE_DISPLAY_NAME_MAPPINGS as PROMPT_NAMES
from .powder_grid import NODE_CLASS_MAPPINGS as GRID_NODES, NODE_DISPLAY_NAME_MAPPINGS as GRID_NAMES
from .powder_conditioner import NODE_CLASS_MAPPINGS as COND_NODES, NODE_DISPLAY_NAME_MAPPINGS as COND_NAMES
from .powder_styler import NODE_CLASS_MAPPINGS as STYLER_NODES, NODE_DISPLAY_NAME_MAPPINGS as STYLER_NAMES

NODE_CLASS_MAPPINGS = {**LORA_NODES, **PROMPT_NODES, **GRID_NODES, **COND_NODES, **STYLER_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**LORA_NAMES, **PROMPT_NAMES, **GRID_NAMES, **COND_NAMES, **STYLER_NAMES}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
